#!/usr/bin/env python3
"""
send_email.py - Institutional Earnings Risk Report
Renders analysis_raw.json from the modern analysis_engine pipeline.
Uses .env for Gmail credentials.
"""

import json
import smtplib
import os
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

WORKSPACE = Path.home() / ".openclaw" / "workspace"
DATA_DIR = WORKSPACE / "data"
INPUT_FILE = DATA_DIR / "analysis" / "analysis_raw.json"
LOG_FILE = DATA_DIR / "logs" / "pipeline.log"


def log(msg):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(LOG_FILE, "a") as f:
        f.write(f"[{timestamp}] EMAIL: {msg}\n")
    print(f"[{timestamp}] EMAIL: {msg}")


def load_analysis():
    if not INPUT_FILE.exists():
        log(f"Missing file: {INPUT_FILE}")
        return [], {}
    with open(INPUT_FILE) as f:
        data = json.load(f)
    
    # Handle both old format (array) and new format (object with metadata)
    if isinstance(data, dict) and "candidates" in data:
        return data.get("candidates", []), data.get("metadata", {})
    return data, {}


def format_percent(value):
    """Format decimal probability as percentage."""
    if value is None:
        return "-"
    return f"{value * 100:.0f}%"


def format_move(value):
    """Format move percentage."""
    if value is None:
        return "-"
    return f"{value:+.1f}%"


def build_no_candidates_email(metadata=None):
    """Build email for zero-candidate scenario."""
    if metadata is None:
        metadata = {}
    
    metadata_html = ""
    if metadata.get("total_candidates") is not None:
        metadata_html = f"""
    <div style="background-color: #f8f9fa; padding: 12px; border-radius: 4px; margin-bottom: 16px;">
        <h4 style="margin: 0 0 8px 0;">Earnings Scan Summary</h4>
        <p style="margin: 4px 0;">
            <strong>Total Candidates:</strong> {metadata.get('total_candidates', '-')}
        </p>
    </div>
        """

    html = f"""
    <html>
    <body style="font-family: Arial; font-size:13px;">

    <h2>Earnings Analysis Report</h2>

    {metadata_html}

    <div style="background-color: #f8f9fa; padding: 20px; border-radius: 4px; margin: 20px 0;">
        <h3 style="margin: 0 0 10px 0;">No Candidates Analyzed</h3>
        <p style="margin: 0;">
            No earnings candidates were found or analyzed in this pipeline run.
        </p>
    </div>

    <p><strong>Pipeline Result:</strong> 0 candidates</p>

    <br><br>
    <small>Generated by Mission Control Pipeline</small>

    </body>
    </html>
    """

    return html


def build_html(data, metadata=None):
    """Build HTML report from analysis_engine output."""
    if metadata is None:
        metadata = {}

    if not data:
        return None

    # Sort by price move magnitude (absolute) - most volatile first
    data.sort(
        key=lambda x: abs(x.get("key_movement", {}).get("magnitude", 0)),
        reverse=True
    )

    total = len(data)
    
    # Count significant moves
    significant_up = len([x for x in data if x.get("key_movement", {}).get("magnitude", 0) > 5])
    significant_down = len([x for x in data if x.get("key_movement", {}).get("magnitude", 0) < -5])

    table_rows = ""

    for t in data:
        ticker = t.get("ticker", "")
        
        # Load full analysis report from report_path
        full_report = {}
        report_path = t.get("report_path")
        if report_path:
            try:
                with open(report_path) as f:
                    full_report = json.load(f)
            except Exception:
                pass
        
        # Market data (from compact response)
        market = t.get("market", {})
        price = market.get("price")
        if price is None:
            # Try to get from options_context in full report
            options_ctx = full_report.get("options_context", {})
            price = options_ctx.get("underlying_price")
        price_display = f"${price:.2f}" if price else "-"
        
        # Options EM (from compact response)
        options = t.get("options", {})
        em = options.get("em_percent")
        if em is None:
            options_ctx = full_report.get("options_context", {})
            em = options_ctx.get("implied_move")
        em_display = f"{em:.1f}%" if em is not None else "-"
        
        # Use full_report for analysis fields, fallback to compact data
        # Historical probabilities
        hist = full_report.get("historical_volatility", t.get("historical_volatility", {}))
        p1 = format_percent(hist.get("down_1x"))
        p15 = format_percent(hist.get("down_1_5x"))
        p2 = format_percent(hist.get("down_2x"))
        
        # Technical analysis
        tech = full_report.get("technical_analysis", t.get("technical_analysis", {}))
        trend = tech.get("trend", "neutral").upper()
        
        # Trade desk summary
        trade_desk = full_report.get("trade_desk_analysis", t.get("trade_desk_analysis", {}))
        summary = trade_desk.get("trade_desk_summary")
        if not summary:
            summary = "No summary available."
        
        # Truncate summary for table
        summary_short = summary[:80] + "..." if len(summary) > 80 else summary
        
        # Trend color
        trend_color = {
            "BULLISH": "#1e7e34",
            "BEARISH": "#c92a2a",
            "NEUTRAL": "#666"
        }.get(trend, "#666")

        table_rows += f"""
        <tr>
            <td><strong>{ticker}</strong></td>
            <td>{price_display}</td>
            <td>{em_display}</td>
            <td style="color:{trend_color}; font-weight:bold;">{trend}</td>
            <td>{p1}</td>
            <td><strong>{p15}</strong></td>
            <td>{p2}</td>
            <td>{summary_short}</td>
        </tr>
        """

    detail_sections = ""

    for t in data:
        ticker = t.get("ticker", "")
        
        # Load full analysis report from report_path
        full_report = {}
        report_path = t.get("report_path")
        if report_path:
            try:
                with open(report_path) as f:
                    full_report = json.load(f)
            except Exception:
                pass
        
        # Market data - fall back to options_context if not available
        market = t.get("market", {})
        price = market.get("price")
        if price is None:
            options_ctx = full_report.get("options_context", t.get("options_context", {}))
            price = options_ctx.get("underlying_price")
        price_display = f"${price:.2f}" if price else "-"
        
        # Options - fall back to options_context if not available
        options = t.get("options", {})
        em = options.get("em_percent")
        if em is None:
            options_ctx = full_report.get("options_context", t.get("options_context", {}))
            em = options_ctx.get("implied_move")
        em_display = f"{em:.1f}%" if em is not None else "-"
        
        # Report date
        report = t.get("report", {})
        report_date = report.get("date", "TBD")
        
        # Key movement
        key_move = full_report.get("key_movement", t.get("key_movement", {}))
        move_magnitude = key_move.get("magnitude")
        move_type = key_move.get("type", "unknown")
        move_display = format_move(move_magnitude)
        
        # Historical probabilities
        hist = full_report.get("historical_volatility", t.get("historical_volatility", {}))
        p1 = format_percent(hist.get("down_1x"))
        p15 = format_percent(hist.get("down_1_5x"))
        p2 = format_percent(hist.get("down_2x"))
        median_move = format_percent(hist.get("median_move"))
        
        # Technical analysis
        tech = full_report.get("technical_analysis", t.get("technical_analysis", {}))
        trend = tech.get("trend", "neutral").upper()
        sma_20 = tech.get("sma_20")
        sma_50 = tech.get("sma_50")
        
        # Options context
        options_ctx = full_report.get("options_context", t.get("options_context", {}))
        implied = options_ctx.get("implied_move")
        implied_display = f"{implied:.1f}%" if implied else "-"
        
        # Trade desk analysis
        trade_desk = full_report.get("trade_desk_analysis", t.get("trade_desk_analysis", {}))
        summary = trade_desk.get("trade_desk_summary")
        if not summary:
            summary = "No summary available."
        movement_diag = trade_desk.get("movement_diagnosis", "")
        sentiment = trade_desk.get("sentiment_regime", "")
        csp_viability = trade_desk.get("csp_viability", "")
        
        # Earnings context
        earnings_ctx = full_report.get("earnings_context", t.get("earnings_context", {}))
        earnings_interp = earnings_ctx.get("interpretation", "N/A")
        
        # Sector context
        sector_ctx = full_report.get("sector_context", t.get("sector_context", {}))
        sector_etf = t.get("sector_etf", full_report.get("sector_etf"))
        sector_return = sector_ctx.get("relative_performance")
        sector_return_display = format_percent(sector_return / 100) if sector_return else "-"
        sector_interp = sector_ctx.get("interpretation", "")
        
        # Sector ETF display
        sector_display = f"{sector_etf}" if sector_etf else "-"
        
        # Key Catalysts - from material_events (priority: reason > headline > category)
        # Skip generic/uninformative reasons
        GENERIC_REASONS = {'ceo', 'cfo', 'coo', 'cto', 'acquisition', 'merger', 
                          'earnings', 'guidance', 'revenue', 'eps', 'dividend',
                          'stock', 'market', 'sector', 'index', 'news', 'report'}
        
        material = full_report.get("material_events", t.get("material_events", []))
        catalysts_seen = set()
        catalysts = []
        for m in material[:5]:  # Check more to get top 2 unique
            # Priority: reason > headline > category
            reason = m.get("reason", "")
            headline = m.get("headline", "")
            category = m.get("category", "")
            
            # Choose best available text
            # Skip if reason is generic/uninformative
            if reason and len(reason) >= 5 and reason.lower() not in GENERIC_REASONS:
                text = reason
            elif headline and len(headline) >= 10:
                text = headline[:80]  # Truncate long headlines
            elif category and len(category) >= 5 and category.lower() not in GENERIC_REASONS:
                text = category
            else:
                continue  # Skip short/empty/generic texts
            
            # Deduplicate
            text_lower = text.lower()
            if text_lower not in catalysts_seen and len(catalysts) < 2:
                catalysts_seen.add(text_lower)
                catalysts.append(f"• {text}")
        
        catalysts_display = "<br>".join(catalysts) if catalysts else "-"
        
        header = (
            f"{ticker} — {price_display} | "
            f"EM {em_display} | "
            f"Report: {report_date}"
        )

        detail_sections += f"""
        <hr>
        <h3>{header}</h3>

        <table style="width:100%; border-collapse: collapse; margin-bottom: 12px;">
        <tr>
            <td style="padding: 4px; width: 50%;">
                <strong>Expected Move:</strong> {implied_display}<br>
                <strong>Historical Median:</strong> {median_move}<br>
                <strong>ATM IV:</strong> {options_ctx.get('atm_iv', '-')}
            </td>
            <td style="padding: 4px; width: 50%;">
                <strong>Trend:</strong> {trend}<br>
                <strong>Sector ETF:</strong> {sector_display}<br>
                <strong>Sector Relative:</strong> {sector_return_display}
            </td>
        </tr>
        </table>

        <p><strong>Key Catalysts:</strong><br>
        {catalysts_display}</p>

        <p><strong>Trade Desk View:</strong><br>
        {summary}</p>

        <p><strong>CSP Viability:</strong> {csp_viability}</p>

        <p><strong>Downside Probability:</strong><br>
        ↓1x: {p1} | ↓1.5x: {p15} | ↓2x: {p2}</p>
        """

    # Metadata summary
    metadata_html = ""
    if metadata.get("total_candidates") is not None:
        metadata_html = f"""
    <div style="background-color: #f8f9fa; padding: 12px; border-radius: 4px; margin-bottom: 16px;">
        <h4 style="margin: 0 0 8px 0;">Earnings Scan Summary</h4>
        <p style="margin: 4px 0;">
            <strong>Total Candidates:</strong> {metadata.get('total_candidates', '-')}
        </p>
    </div>
        """

    html = f"""
    <html>
    <body style="font-family: Arial; font-size:13px;">

    <h2>Earnings Analysis Report</h2>

    {metadata_html}

    <p>
    <strong>Total Analyzed:</strong> {total} |
    <strong>Significant Up:</strong> {significant_up} |
    <strong>Significant Down:</strong> {significant_down}
    </p>

    <h3>Candidates Overview</h3>

    <table style="border-collapse: collapse; width:100%;" border="1" cellpadding="6">
    <tr style="background-color:#f1f3f5;">
        <th>Ticker</th>
        <th>Price</th>
        <th>Exp Move</th>
        <th>Trend</th>
        <th>↓1x</th>
        <th>↓1.5x</th>
        <th>↓2x</th>
        <th>Summary</th>
    </tr>
    {table_rows}
    </table>

    {detail_sections}

    <br><br>
    <small>Generated by Mission Control Pipeline (analysis_engine)</small>

    </body>
    </html>
    """

    return html


def send_email(html):
    """Send email via Gmail SMTP."""
    sender = os.environ.get("GMAIL_USER")
    password = os.environ.get("GMAIL_APP_PASSWORD")
    recipient = "guanwu87@gmail.com"

    if not sender or not password:
        log("Missing Gmail credentials in .env file")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = "Earnings Analysis Report"
    msg["From"] = sender
    msg["To"] = recipient

    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(sender, password)
            server.send_message(msg)
        log("Email sent successfully")
    except Exception as e:
        log(f"Email send failed: {e}")


def main():
    log("=== Starting send_email.py ===")

    data, metadata = load_analysis()

    if not data:
        log("Zero candidates — sending 'no setups' email")
        html = build_no_candidates_email(metadata)
        send_email(html)
        return

    html = build_html(data, metadata)

    if not html:
        log("HTML build failed")
        return

    send_email(html)
    log("=== Completed ===")


if __name__ == "__main__":
    main()
